# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://colsit.com
title: ColSIT
email: admin@colsit.com
author: Said Fayad
description: > # "Write an awesome description for your new site here. 
  Soluciones de infraestructura IT y administración de servidores Linux. Especialista en optimización de sistemas, pipelines de CI/CD y seguridad en la nube para sectores financieros y retail.
copyright: 'Copyright &copy; 2008 ColSIT . All Rights Reserved.'
credits: 

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: twitter
    url: https://twitter.com/adalid_negro
  - title: github
    url: https://github.com/adalidnegro
  - title: linkedin
    url: https://www.linkedin.com/company/colsit-sas/
